name: Deploy to Hostinger
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: hostinger/deploy-on-vps@v1
        with:
          
          api-key: ${{ secrets.HOSTINGER_API_KEY }}
          virtual-machine: ${{ secrets.HOSTINGER_VM_ID }}
          
          project-name: "auto-workshop-website" 
